class TournamentGameConfig {
  final String gameName;
  final String icon;
  final String defaultMode;
  final String defaultMap;
  final int defaultSlots;
  final List<String> modes;
  final List<String> maps;
  final String platform;
  final List<String> victoryKeywords;

  const TournamentGameConfig({
    required this.gameName,
    required this.icon,
    required this.defaultMode,
    required this.defaultMap,
    required this.defaultSlots,
    required this.modes,
    required this.maps,
    required this.platform,
    required this.victoryKeywords,
  });
}

/// Exact list of game categories requested:
/// BGMI, PUBG Mobile, Garena Free Fire, Free Fire Max, COD Mobile, COD Warzone,
/// Valorant, Fortnite, Apex Legends, Counter-Strike 2, Mobile Legends Bang Bang,
/// League of Legends, Clash Royale, Brawl Stars, Minecraft, Roblox, EA Sports FC 25,
/// 8 Ball Pool, Ludo King.
const List<String> kExactGameCategories = [
  'BGMI',
  'PUBG Mobile',
  'Garena Free Fire',
  'Free Fire Max',
  'COD Mobile',
  'COD Warzone',
  'Valorant',
  'Fortnite',
  'Apex Legends',
  'Counter-Strike 2',
  'Mobile Legends Bang Bang',
  'League of Legends',
  'Clash Royale',
  'Brawl Stars',
  'Minecraft',
  'Roblox',
  'EA Sports FC 25',
  '8 Ball Pool',
  'Ludo King',
];

const Map<String, TournamentGameConfig> kTournamentGameConfigs = {
  'BGMI': TournamentGameConfig(
    gameName: 'BGMI',
    icon: '🪖',
    defaultMode: 'Warehouse TDM',
    defaultMap: 'Warehouse',
    defaultSlots: 2,
    modes: ['Warehouse TDM', 'TDM 4v4', 'Classic Scrim'],
    maps: ['Warehouse', 'Erangel', 'Livik'],
    platform: 'Mobile',
    victoryKeywords: ['VICTORY', 'WINNER WINNER CHICKEN DINNER', '#1/', '#1 ', 'CHICKEN DINNER', 'BLUE TEAM WINS'],
  ),
  'PUBG Mobile': TournamentGameConfig(
    gameName: 'PUBG Mobile',
    icon: '🪂',
    defaultMode: 'Warehouse TDM',
    defaultMap: 'Warehouse',
    defaultSlots: 2,
    modes: ['Warehouse TDM', 'TDM 4v4', 'Classic Scrim'],
    maps: ['Warehouse', 'Erangel', 'Sanhok'],
    platform: 'Mobile',
    victoryKeywords: ['VICTORY', 'WINNER WINNER CHICKEN DINNER', '#1/', '#1 ', 'CHICKEN DINNER', 'BLUE TEAM WINS'],
  ),
  'Garena Free Fire': TournamentGameConfig(
    gameName: 'Garena Free Fire',
    icon: '🔥',
    defaultMode: 'Clash Squad',
    defaultMap: 'Bermuda',
    defaultSlots: 4,
    modes: ['Clash Squad', 'Lone Wolf 1v1', 'Battle Royale'],
    maps: ['Bermuda', 'Kalahari', 'Purgatory'],
    platform: 'Mobile',
    victoryKeywords: ['BOOYAH', 'BOOYAH!', 'VICTORY', '#1'],
  ),
  'Free Fire Max': TournamentGameConfig(
    gameName: 'Free Fire Max',
    icon: '⚡',
    defaultMode: 'Clash Squad',
    defaultMap: 'Bermuda',
    defaultSlots: 4,
    modes: ['Clash Squad', 'Lone Wolf 1v1', 'Battle Royale'],
    maps: ['Bermuda', 'Alpine', 'Kalahari'],
    platform: 'Mobile',
    victoryKeywords: ['BOOYAH', 'BOOYAH!', 'VICTORY', '#1'],
  ),
  'COD Mobile': TournamentGameConfig(
    gameName: 'COD Mobile',
    icon: '🎖️',
    defaultMode: 'TDM',
    defaultMap: 'Crash',
    defaultSlots: 2,
    modes: ['TDM', 'Search & Destroy', '1v1 Duel'],
    maps: ['Crash', 'Nuketown', 'Crossfire'],
    platform: 'Mobile',
    victoryKeywords: ['VICTORY', 'WINNER', 'MATCH WON', 'FIRST PLACE'],
  ),
  'COD Warzone': TournamentGameConfig(
    gameName: 'COD Warzone',
    icon: '🎯',
    defaultMode: 'Resurgence',
    defaultMap: 'Rebirth Island',
    defaultSlots: 4,
    modes: ['Resurgence', 'Battle Royale', 'Custom Lobby'],
    maps: ['Rebirth Island', 'Urzikstan', 'Fortune\'s Keep'],
    platform: 'Console',
    victoryKeywords: ['WARZONE VICTORY', 'VICTORY', '#1', 'WINNER'],
  ),
  'Valorant': TournamentGameConfig(
    gameName: 'Valorant',
    icon: '⚔️',
    defaultMode: 'Spike Rush',
    defaultMap: 'Ascent',
    defaultSlots: 2,
    modes: ['Spike Rush', 'Custom 1v1', 'Deathmatch', 'Competitive 5v5'],
    maps: ['Ascent', 'Bind', 'Haven', 'Split'],
    platform: 'PC',
    victoryKeywords: ['VICTORY', 'MATCH WON', 'SPIKE DEFUSED', 'TEAM ACE'],
  ),
  'Fortnite': TournamentGameConfig(
    gameName: 'Fortnite',
    icon: '⛏️',
    defaultMode: 'Box Fight 1v1',
    defaultMap: 'Creative Arena',
    defaultSlots: 2,
    modes: ['Box Fight 1v1', '1v1 Build Fight', 'Battle Royale'],
    maps: ['Creative Arena', 'Battle Royale Island', 'Zone Wars'],
    platform: 'Cross-Platform',
    victoryKeywords: ['VICTORY ROYALE', '#1 VICTORY ROYALE', 'VICTORY', 'YOU PLACED #1'],
  ),
  'Apex Legends': TournamentGameConfig(
    gameName: 'Apex Legends',
    icon: '🏹',
    defaultMode: 'Arenas 3v3',
    defaultMap: 'Party Crasher',
    defaultSlots: 2,
    modes: ['Arenas 3v3', 'Custom 1v1 Arena', 'Trios'],
    maps: ['Party Crasher', 'World\'s Edge', 'Olympus'],
    platform: 'PC',
    victoryKeywords: ['YOU ARE THE APEX CHAMPIONS', 'CHAMPIONS', 'CHAMPION', 'VICTORY'],
  ),
  'Counter-Strike 2': TournamentGameConfig(
    gameName: 'Counter-Strike 2',
    icon: '💣',
    defaultMode: 'Wingman 2v2',
    defaultMap: 'Dust II',
    defaultSlots: 4,
    modes: ['Wingman 2v2', 'Competitive 5v5', '1v1 Aim Duel'],
    maps: ['Dust II', 'Mirage', 'Inferno'],
    platform: 'PC',
    victoryKeywords: ['COUNTER-TERRORISTS WIN', 'TERRORISTS WIN', 'VICTORY', 'MATCH POINT'],
  ),
  'Mobile Legends Bang Bang': TournamentGameConfig(
    gameName: 'Mobile Legends Bang Bang',
    icon: '🛡️',
    defaultMode: 'Classic 5v5',
    defaultMap: 'Land of Dawn',
    defaultSlots: 2,
    modes: ['Classic 5v5', 'Custom 1v1', 'Brawl Mode'],
    maps: ['Land of Dawn', 'Brawl Battlefield'],
    platform: 'Mobile',
    victoryKeywords: ['VICTORY', 'VICTORY!', 'MVP', 'SAVAGE', 'LEGENDARY'],
  ),
  'League of Legends': TournamentGameConfig(
    gameName: 'League of Legends',
    icon: '🧙‍♂️',
    defaultMode: 'ARAM 1v1',
    defaultMap: 'Howling Abyss',
    defaultSlots: 2,
    modes: ['ARAM 1v1', '1v1 Mid Only', 'Custom 5v5'],
    maps: ['Howling Abyss', 'Summoner\'s Rift'],
    platform: 'PC',
    victoryKeywords: ['VICTORY', 'VICTORY!', 'NEXUS DESTROYED'],
  ),
  'Clash Royale': TournamentGameConfig(
    gameName: 'Clash Royale',
    icon: '👑',
    defaultMode: 'Friendly 1v1',
    defaultMap: 'Legendary Arena',
    defaultSlots: 2,
    modes: ['Friendly 1v1', 'Triple Elixir', 'Draft Battle'],
    maps: ['Legendary Arena', 'Royal Arena'],
    platform: 'Mobile',
    victoryKeywords: ['VICTORY', 'VICTORY!', '3 CROWNS', 'WINNER'],
  ),
  'Brawl Stars': TournamentGameConfig(
    gameName: 'Brawl Stars',
    icon: '🥊',
    defaultMode: 'Bounty 3v3',
    defaultMap: 'Shooting Star',
    defaultSlots: 2,
    modes: ['Bounty 3v3', 'Solo Showdown', 'Gem Grab 3v3'],
    maps: ['Shooting Star', 'Cavern Churn'],
    platform: 'Mobile',
    victoryKeywords: ['VICTORY', 'STAR PLAYER', 'RANK 1', '#1'],
  ),
  'Minecraft': TournamentGameConfig(
    gameName: 'Minecraft',
    icon: '🧱',
    defaultMode: 'PvP Duel 1v1',
    defaultMap: 'Gladiator Arena',
    defaultSlots: 2,
    modes: ['PvP Duel 1v1', 'Bedwars', 'Skywars'],
    maps: ['Gladiator Arena', 'Bedwars Arena'],
    platform: 'Cross-Platform',
    victoryKeywords: ['VICTORY', 'YOU WON', 'WINNER'],
  ),
  'Roblox': TournamentGameConfig(
    gameName: 'Roblox',
    icon: '🕹️',
    defaultMode: 'BedWars 1v1',
    defaultMap: 'Custom Arena',
    defaultSlots: 2,
    modes: ['BedWars 1v1', 'Arsenal 1v1', 'Custom Server'],
    maps: ['Custom Arena', 'Main World'],
    platform: 'Cross-Platform',
    victoryKeywords: ['VICTORY', 'WINNER', 'YOU WON'],
  ),
  'EA Sports FC 25': TournamentGameConfig(
    gameName: 'EA Sports FC 25',
    icon: '⚽',
    defaultMode: 'Head to Head 1v1',
    defaultMap: 'Champions Stadium',
    defaultSlots: 2,
    modes: ['Head to Head 1v1', 'Friendly Match', 'Ultimate Team'],
    maps: ['Champions Stadium', 'Santiago Bernabéu'],
    platform: 'Console',
    victoryKeywords: ['FULL TIME', 'VICTORY', 'WIN', 'WINNER'],
  ),
  '8 Ball Pool': TournamentGameConfig(
    gameName: '8 Ball Pool',
    icon: '🎱',
    defaultMode: '1v1 Classic',
    defaultMap: 'London Pub',
    defaultSlots: 2,
    modes: ['1v1 Classic', 'Tournament 8-Player'],
    maps: ['London Pub', 'Tokyo Warrior'],
    platform: 'Mobile',
    victoryKeywords: ['YOU WIN', 'WINNER', 'WON'],
  ),
  'Ludo King': TournamentGameConfig(
    gameName: 'Ludo King',
    icon: '🎲',
    defaultMode: 'Quick 2/4 Player',
    defaultMap: 'Classic Board',
    defaultSlots: 2,
    modes: ['Quick 2/4 Player', '1v1 Classic', '4 Player Classic'],
    maps: ['Classic Board', 'Nature Board'],
    platform: 'Mobile',
    victoryKeywords: ['WINNER', 'RANK 1', 'WON', '#1'],
  ),
};

TournamentGameConfig getGameConfig(String gameName) {
  return kTournamentGameConfigs[gameName] ??
      TournamentGameConfig(
        gameName: gameName,
        icon: '🎮',
        defaultMode: 'Custom Match',
        defaultMap: 'Default Map',
        defaultSlots: 2,
        modes: ['Custom Match', '1v1 Duel'],
        maps: ['Default Map'],
        platform: 'Mobile',
        victoryKeywords: ['VICTORY', 'WINNER', 'WON'],
      );
}
