allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

// یہ نیا حصہ شامل کیا گیا ہے تاکہ تمام لائبریریاں SDK 35 استعمال کریں
subprojects {
    afterEvaluate { project ->
        if (project.hasProperty('android')) {
            project.android {
                if (namespace == null) {
                    namespace project.group
                }
                compileSdkVersion 35
            }
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}