android {
    namespace = "com.gameskhabar.games_khabar"
    compileSdk 36
    ndkVersion = "28.2.13676358"

    compileOptions {
        coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }
    defaultConfig {
        applicationId "com.gameskhabar.games_khabar"
        minSdk 24
        targetSdk 36
        versionCode 1
        versionName "1.0"
    }
    // baqi same...
}